# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import runtime_pb2 as investigation_dot_runtime_dot_v1_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in investigation/runtime/v1/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScenarioRuntimeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRun = channel.unary_unary(
                '/investigation.runtime.v1.ScenarioRuntime/CreateRun',
                request_serializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.CreateRunRequest.SerializeToString,
                response_deserializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.Run.FromString,
                _registered_method=True)
        self.LeaseTask = channel.unary_unary(
                '/investigation.runtime.v1.ScenarioRuntime/LeaseTask',
                request_serializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.LeaseTaskRequest.SerializeToString,
                response_deserializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.LeaseTaskResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/investigation.runtime.v1.ScenarioRuntime/CallTool',
                request_serializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.CallToolRequest.SerializeToString,
                response_deserializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.ToolCallResponse.FromString,
                _registered_method=True)
        self.AbortTask = channel.unary_unary(
                '/investigation.runtime.v1.ScenarioRuntime/AbortTask',
                request_serializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.AbortTaskRequest.SerializeToString,
                response_deserializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.AbortTaskResponse.FromString,
                _registered_method=True)
        self.CloseRun = channel.unary_unary(
                '/investigation.runtime.v1.ScenarioRuntime/CloseRun',
                request_serializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.CloseRunRequest.SerializeToString,
                response_deserializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.CloseRunResponse.FromString,
                _registered_method=True)


class ScenarioRuntimeServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaseTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScenarioRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRun,
                    request_deserializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.CreateRunRequest.FromString,
                    response_serializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.Run.SerializeToString,
            ),
            'LeaseTask': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaseTask,
                    request_deserializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.LeaseTaskRequest.FromString,
                    response_serializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.LeaseTaskResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.CallToolRequest.FromString,
                    response_serializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.ToolCallResponse.SerializeToString,
            ),
            'AbortTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortTask,
                    request_deserializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.AbortTaskRequest.FromString,
                    response_serializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.AbortTaskResponse.SerializeToString,
            ),
            'CloseRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseRun,
                    request_deserializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.CloseRunRequest.FromString,
                    response_serializer=investigation_dot_runtime_dot_v1_dot_runtime__pb2.CloseRunResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'investigation.runtime.v1.ScenarioRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('investigation.runtime.v1.ScenarioRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScenarioRuntime:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/investigation.runtime.v1.ScenarioRuntime/CreateRun',
            investigation_dot_runtime_dot_v1_dot_runtime__pb2.CreateRunRequest.SerializeToString,
            investigation_dot_runtime_dot_v1_dot_runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaseTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/investigation.runtime.v1.ScenarioRuntime/LeaseTask',
            investigation_dot_runtime_dot_v1_dot_runtime__pb2.LeaseTaskRequest.SerializeToString,
            investigation_dot_runtime_dot_v1_dot_runtime__pb2.LeaseTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/investigation.runtime.v1.ScenarioRuntime/CallTool',
            investigation_dot_runtime_dot_v1_dot_runtime__pb2.CallToolRequest.SerializeToString,
            investigation_dot_runtime_dot_v1_dot_runtime__pb2.ToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/investigation.runtime.v1.ScenarioRuntime/AbortTask',
            investigation_dot_runtime_dot_v1_dot_runtime__pb2.AbortTaskRequest.SerializeToString,
            investigation_dot_runtime_dot_v1_dot_runtime__pb2.AbortTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/investigation.runtime.v1.ScenarioRuntime/CloseRun',
            investigation_dot_runtime_dot_v1_dot_runtime__pb2.CloseRunRequest.SerializeToString,
            investigation_dot_runtime_dot_v1_dot_runtime__pb2.CloseRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
